### ISSUE TITLE
The application is exited

### ISSUE THREAD

**Issue by mohanad87m** [harrowmykel/flutter_mobile_vision_2#15]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.mobile_vision">
    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.CAMERA" />
   <application
        android:label="mobile_vision"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>
        

       <activity android:name="ng.com.piccmaq.flutter.flutter_mobile_vision_2.barcode.BarcodeCaptureActivity" />
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by mohanad87m** [comment]
D/OplusCameraStatisticsManager( 3060): addInfo, eventMap: {halLevel=1, cameraId=0, pkgName=com.example.mobile_vision, connentTime=1682797800479, apLevel=1}
D/OplusCameraStatisticsManager( 3060): addInfo, eventMap: {halLevel=1, cameraId=0, disconnectTime=1682797800504, pkgName=com.example.mobile_vision, connentTime=1682797800479, apLevel=1, timeCost=25}
W/libc    ( 3060): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 3060): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 3060): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 3060): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 3060): Access denied finding property "vendor.camera.aux.packagelist"
I/OplusCameraUtils( 3060): current activityName: com.example.mobile_vision.MainActivity
I/OplusCameraUtils( 3060): getComponentName, componentName: com.example.mobile_vision/com.example.mobile_vision.MainActivity, packageName:com.example.mobile_vision, activityName:com.example.mobile_vision.MainActivity
D/OplusCameraStatisticsManager( 3060): addInfo, eventMap: {halLevel=1, cameraId=1, pkgName=com.example.mobile_vision, connentTime=1682797800536, apLevel=1}
D/OplusCameraStatisticsManager( 3060): addInfo, eventMap: {halLevel=1, cameraId=1, disconnectTime=1682797800545, pkgName=com.example.mobile_vision, connentTime=1682797800536, apLevel=1, timeCost=9}
I/Quality ( 3060): Skipped: false 8 cost 132.58783 refreshRate 0 processName com.example.mobile_vision
D/SurfaceComposerClient( 3060): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
D/ViewRootImpl[MainActivity]( 3060):  debugCancelDraw  cancelDraw=false,count = 355,android.view.ViewRootImpl@94a6134
D/SurfaceComposerClient( 3060): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
E/MethodChannel#flutter_mobile_vision_2( 3060): Failed to handle method call
E/MethodChannel#flutter_mobile_vision_2( 3060): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.mobile_vision/ng.com.piccmaq.flutter.flutter_mobile_vision_2.ocr.OcrCaptureActivity}; have you declared this activity in your AndroidManifest.xml?
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1770)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.app.Activity.startActivityForResult(Activity.java:5473)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.app.Activity.startActivityForResult(Activity.java:5426)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at ng.com.piccmaq.flutter.flutter_mobile_vision_2.FlutterMobileVisionDelegate.launchIntent(FlutterMobileVisionDelegate.java:254)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at ng.com.piccmaq.flutter.flutter_mobile_vision_2.FlutterMobileVisionDelegate.read(FlutterMobileVisionDelegate.java:124)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at ng.com.piccmaq.flutter.flutter_mobile_vision_2.FlutterMobileVisionPlugin.onMethodCall(FlutterMobileVisionPlugin.java:182)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.os.Looper.loopOnce(Looper.java:233)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.os.Looper.loop(Looper.java:344)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MethodChannel#flutter_mobile_vision_2( 3060): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
D/AndroidRuntime( 3060): Shutting down VM
E/AndroidRuntime( 3060): FATAL EXCEPTION: main
E/AndroidRuntime( 3060): Process: com.example.mobile_vision, PID: 3060
E/AndroidRuntime( 3060): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 3060): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 3060): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:268)
E/AndroidRuntime( 3060): 	at ng.com.piccmaq.flutter.flutter_mobile_vision_2.FlutterMobileVisionPlugin$MethodResultWrapper$2.run(FlutterMobileVisionPlugin.java:141)
E/AndroidRuntime( 3060): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3060): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3060): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime( 3060): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime( 3060): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime( 3060): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3060): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime( 3060): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
I/Process ( 3060): Sending signal. PID: 3060 SIG: 9
Lost connection to device.

**Comment by mohanad87m** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.mobile_vision">
    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.CAMERA" />
   <application
        android:label="mobile_vision"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>
        

       <activity android:name="ng.com.piccmaq.flutter.flutter_mobile_vision_2.barcode.BarcodeCaptureActivity" />
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
